[dev-docsite]
alias = "dd"
description = "starts the documentation site (https://komodo.docs.neureka.dev/) in dev mode"
cmd = "yarn && yarn start"

[build-docsite]
alias = "bd"
description = "builds the documentation site (https://komodo.docs.neureka.dev/)"
cmd = "yarn && yarn build"

[serve-docsite]
alias = "sd"
description = "builds and serves the built documentation site (https://komodo.docs.neureka.dev/)"
after = ["build-docsite"]
cmd = "yarn serve"

[publish-docsite]
description = "publishes the documentation site (https://komodo.docs.neureka.dev/) to github pages"
cmd = "yarn && yarn deploy"